# -*- coding: utf-8 -*-
"""SQL_mean_median_session.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DBLNcyXKQRmL4N4SR2JuU3qf0ikrBudd
"""

# Авторизируемся

from google.colab import auth
auth.authenticate_user()
print('Authenticated')

# Commented out IPython magic to ensure Python compatibility.
# # Формируем запрос BigQuerry 
# 
# %%bigquery dataset --project petki-377605
# 
# WITH per_customer AS (SELECT customer
#                             ,SUM(tm_session) time_per_customer
#                             ,COUNTIF(tm_session = 0)+1 sess_per_customer
#                       FROM (SELECT customer
#                                   ,tm
#                                   ,CASE
#                                       WHEN tm_session > 1800 THEN 0
#                                       ELSE tm_session
#                                     END tm_session
#                             FROM (SELECT ym_pv_clientID customer
#                                         ,ym_pv_dateTime tm
#                                         ,DATE_DIFF(ym_pv_dateTime, LAG(ym_pv_dateTime) OVER(PARTITION BY ym_pv_clientID ORDER BY ym_pv_dateTime), second) tm_session
#                                   FROM `petki-377605.Test.toretto_car`) q1
#                             ORDER BY customer, tm) q2
#                       GROUP BY q2.customer),
# med_ses AS (SELECT CAST(max(median) AS INT) median_sessions
#                   ,1 id
#             FROM (SELECT PERCENTILE_CONT(time_per_customer, 0.5) OVER () median
#                   FROM per_customer) q3),
# avg_ses AS (SELECT CAST(SUM(time_per_customer)/SUM(sess_per_customer) AS INT) avg_sessions
#                   ,1 id
#             FROM per_customer)
# 
# SELECT TIME_ADD(CAST('00:00:00' AS TIME), INTERVAL avg_sessions second) avg_sessions
#       ,TIME_ADD(CAST('00:00:00' AS TIME), INTERVAL median_sessions second) median_sessions
# FROM avg_ses
# INNER JOIN med_ses USING(id)
#

dataset