# -*- coding: utf-8 -*-
"""SQL_Upload_data.ipynb"

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1E8EIJRA3_F_wFzzUOu6ZnSl8xz9TK001
"""

# Авторизируемся

from google.colab import auth
auth.authenticate_user()
print('Authenticated')

# Commented out IPython magic to ensure Python compatibility.
# # Формируем запрос BigQuerry 
# 
# %%bigquery dataset --project petki-377605
# 
# SELECT *
# FROM `petki-377605.Test.toretto_car`
#

dataset.info()

dataset.sample(10)