# -*- coding: utf-8 -*-
"""SQL_TOP10_brands_and_models.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dctCU3OkSQVo6umGy7bOpIyQyfQxgrQK
"""

# Авторизируемся

from google.colab import auth
auth.authenticate_user()
print('Authenticated')

# Commented out IPython magic to ensure Python compatibility.
# # Формируем запрос BigQuerry 
# 
# %%bigquery dataset --project petki-377605
# 
# WITH arrays1 AS (SELECT arrays
#                 FROM(SELECT SPLIT(CASE
#                                     WHEN STRPOS(str, '?') > 0 THEN LEFT(str, STRPOS(str, '?')-1)
#                                     WHEN STRPOS(str, '#') > 0 THEN LEFT(str, STRPOS(str, '#')-1)
#                                     ELSE str
#                                   END, '/') AS arrays
#                       FROM (SELECT RIGHT(ym_pv_URL, CHAR_LENGTH(ym_pv_URL) - STRPOS(ym_pv_URL, 'car.ru')-6) str
#                             FROM `petki-377605.Test.toretto_car`))
#                 WHERE ARRAY_LENGTH(arrays) > 1 and arrays[OFFSET(0)] in ('new', 'used', 'brand')),
# tab1 AS (SELECT arrays[OFFSET(0)] cat
#                 ,CASE
#                   WHEN ARRAY_LENGTH(arrays) > 1 THEN arrays[OFFSET(1)]
#                   ELSE null
#                 END brands
#                 ,CASE
#                   WHEN ARRAY_LENGTH(arrays) > 2 THEN REPLACE(REPLACE(TRANSLATE(arrays[OFFSET(2)], '1234567890', '$$$$$$$$$$'), '-$', ''), '$', '')
#                   ELSE null
#                 END models
#         FROM arrays1)
# 
# SELECT brands, models, COUNT(*) top
# FROM tab1
# WHERE models IS NOT NULL AND models != ''
# GROUP BY 1, 2
# ORDER BY top DESC
# LIMIT 10
#

dataset.info()

dataset