# -*- coding: utf-8 -*-
"""SQL_traffic_source.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kf1yhs0N7xqkag0u87ohGvrUGEucrIDd
"""

# Авторизируемся

from google.colab import auth
auth.authenticate_user()
print('Authenticated')

# Commented out IPython magic to ensure Python compatibility.
# # Формируем запрос BigQuerry 
# 
# %%bigquery dataset --project petki-377605
# 
# SELECT traffic_source
#       ,COUNT(customer) top
# FROM (SELECT ym_pv_clientID customer
#             ,ym_pv_lastTrafficSource traffic_source
#             ,MIN(ym_pv_dateTime)
#       FROM `petki-377605.Test.toretto_car`
#       WHERE ym_pv_lastTrafficSource NOT IN ('internal', 'external')
#       GROUP BY customer, traffic_source) q1
# GROUP BY traffic_source
# ORDER BY top DESC
#

dataset