# -*- coding: utf-8 -*-
"""SQL_VDP_customer.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iWFwd_wzaEiwGJZFcGE0SXC1iRYEAwBE
"""

# Авторизируемся

from google.colab import auth
auth.authenticate_user()
print('Authenticated')

# Commented out IPython magic to ensure Python compatibility.
# # Формируем запрос BigQuerry 
# 
# %%bigquery dataset --project petki-377605
# 
# SELECT customer
#       ,CASE
#         WHEN device = 1 THEN 'Desktop'ELSE 'Mobile'
#         END device
#       ,traffic_source
#       ,ROUND(COUNTIF(ym_pv_URL LIKE '%/u$%' OR ym_pv_URL LIKE '%/n$%')/COUNT(ym_pv_URL), 3) vpd
# FROM (SELECT TRANSLATE(ym_pv_URL, '1234567890', '$$$$$$$$$$') ym_pv_URL
#             ,ym_pv_deviceCategory device
#             ,ym_pv_lastTrafficSource traffic_source
#             ,ym_pv_clientID customer
#       FROM `petki-377605.Test.toretto_car`
#       WHERE ym_pv_lastTrafficSource NOT IN ('internal', 'external')) q1
# GROUP BY customer, device, traffic_source
# ORDER BY customer, device, traffic_source
#

dataset.info()

dataset.sample(15)